#path to *Data* folder, if empty, the script will fetch the path from the registry
#note that the path has to use double slashes: "C:\\Games\\Oblivion\\Data"
#default: ""
game_folder: ""

#path to plugins.txt file, if empty, the script will fetch the file from its default location
#useful for people with several local Oblivion installs
#note that the path has to use double slashes: "C:\\Games\\Oblivion\\plugins.txt"
#default: ""
plugins_txt_path: ""

#skips mesh generation if set to True, *.lod files are still generated
#useful for small LO updates that do not drastically affect LOD
#or for cases when you need to move MergedLOD.esp
#default: False
skip_mesh_generation: False 

#controls the amount of messages generated in the console and in the log
#"DEBUG" generates the most, "CRITICAL" generates the least
#possible values: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
debug_level: "INFO"

#editorids of worldspaces for which merged meshes will not be generated
worldspaces_to_skip:
 - "AnvilWorld"
 - "BANSkingradOutskirts"
 - "BravilWorld"
 - "CheydinhalWorld"
 - "ChorrolWorld"
 - "E3Kvatch"
 - "ICArboretumDistrict"
 - "ICArenaDistrict"
 - "ICAristocraticDistrict"
 - "ICDiplomaticDistrict"
 - "ICElvenGardensDistrict"
 - "ICImperialPalace"
 - "ICImperialPalaceMQ16"
 - "ICImperialPrisonDistrict"
 - "ICMarketDistrict"
 - "ICTalosPlazaDistrict"
 - "ICTempleDistrict"
 - "ICTempleDistrictMQ16"
 - "ICTheArcaneUniversity"
 - "KvatchEast"
 - "KvatchEntrance"
 - "KvatchPlaza"
 - "LeyawiinWorld"
 - "SENSBliss"
 - "SENSCrucible"
 - "SENSPalace"
 - "SETest"
 - "TestFortRuinsExtWarehouse"
 - "TestGragtown"
 - "TestMatt"
 - "TestWorld"
 - "ToddTestLand2"

#meshes that are not going to be merged -- lowercase without _far
meshes_to_skip:
 - "ulay\\lodwaterplane.nif"
 - "ulbr\\lodwaterplane.nif"
 - "xulac\\lodwaterplane.nif"
 - "xulaw\\lodwaterplane.nif"
 - "xulcflodwaterplane\\lodwaterplane.nif"
 - "xulfe\\lodwaterplane.nif"
 - "xulimpisle\\lodwaterplane.nif"
 - "xulso\\waterlod\\lodwaterplane.nif"
 - "oblivion\\environment\\fxoblivionlightbeamlong01.nif"
 
#list of bsas not loaded by esps
#if doesn't exist will be skipped 
hardcoded_bsas:
 - "Oblivion - Meshes.bsa"
 - "Oblivion - Misc.bsa"
 - "Oblivion - Textures - Compressed.bsa"