#path to *Data* folder, if empty, the script will fetch the path from the registry
game_folder: ""

#path to plugins.txt file, if empty, the script will fetch the file from its default location
#useful for people with several local Oblivion installs
plugins_txt_path: ""

#editorids of worldspaces for which merged meshes will not be generated
worldspaces_to_skip:
 - "AnvilWorld"
 - "BANSkingradOutskirts"
 - "BravilWorld"
 - "CheydinhalWorld"
 - "ChorrolWorld"
 - "E3Kvatch"
 - "ICArboretumDistrict"
 - "ICArenaDistrict"
 - "ICAristocraticDistrict"
 - "ICDiplomaticDistrict"
 - "ICElvenGardensDistrict"
 - "ICImperialPalace"
 - "ICImperialPalaceMQ16"
 - "ICImperialPrisonDistrict"
 - "ICMarketDistrict"
 - "ICTalosPlazaDistrict"
 - "ICTempleDistrict"
 - "ICTempleDistrictMQ16"
 - "ICTheArcaneUniversity"
 - "KvatchEast"
 - "KvatchEntrance"
 - "KvatchPlaza"
 - "LeyawiinWorld"
 - "SENSBliss"
 - "SENSCrucible"
 - "SENSPalace"
 - "SETest"
 - "TestFortRuinsExtWarehouse"
 - "TestGragtown"
 - "TestMatt"
 - "TestWorld"
 - "ToddTestLand2"

#meshes that are not going to be merged -- lowercase without _far
meshes_to_skip:
 - "ulay\\lodwaterplane.nif"
 - "ulbr\\lodwaterplane.nif"
 - "xulac\\lodwaterplane.nif"
 - "xulaw\\lodwaterplane.nif"
 - "xulcflodwaterplane\\lodwaterplane.nif"
 - "xulfe\\lodwaterplane.nif"
 - "xulimpisle\\lodwaterplane.nif"
 - "xulso\\waterlod\\lodwaterplane.nif"