#packs generated LOD files to a bsa
#SkyBSA is required
#essential for performance on MO2
#not needed on Wrye Bash unless you want a tidier setup
#accepted values: True, False
#default: False
write_bsa: False

#skips mesh generation if set to True, *.lod files are still generated
#can be set to True for minor load order changes
#or for cases when you need to move MergedLOD.esm
#accepted values: True, False
#default: False
skip_mesh_generation: False 

###CUSTOM PATH SETTINGS
###NO NEED TO EDIT THESE UNLESS YOU MANUALLY MOVED YOUR GAME FROM THE INSTALLATION DIRECTORY
###OR IF YOU HAVE SEVERAL INSTALLATIONS ON ONE PC

#path to *Data* folder, if it is not defined by the user, the script will fetch the default path from the registry
#note that the path has to use double slashes: "C:\\Games\\Oblivion\\Data"
#default: ""
game_folder: ""

#path to plugins.txt file, if it is not defined by the user, the script will fetch the file from its default location
#useful for people with several local Oblivion installs
#YOU KNOW IF YOU NEED THIS, IF YOU ASK IF YOU NEED TO SET IT, YOU DON'T NEED TO SET IT
#note that the path has to use double slashes: "C:\\Games\\Oblivion\\plugins.txt"
#default: ""
plugins_txt_path: ""

#geometry under water is not merged
water_culling: True

#if True, will add waterplanes (aka 'make lakes in mountains visible in distance') to the merged LOD
waterplanes_generation: True

###ADVANCED SETTINGS, DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING

#you can use custom bsa name prefix if you need to save a esp slot and use a different esp to load the bsa
#note, that you want this esp to be as low in LO as possible, as some mod authors include .lod files to bsa and you want to overwrite them
#also, it is your responsibility to ensure that the esp loader exists
custom_bsa_name: ""

#controls the amount of messages generated in the console and in the log
#"DEBUG" generates the most, "CRITICAL" generates the least
#possible values: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
debug_level: "INFO"

#if set to True, nifs loaded by pyffi will not be unloaded on every merge
#memory-intensive but much faster
#use if you can spare 4GB+ of RAM during generation
#if set to auto, will be set to True if the script detects >=8GB of RAM
#possible options: 'True', 'False', 'Auto' - note quotes
cache_loaded_nifs: 'Auto'

#generates a csv that has statistic on how much each _far mesh contributes to the total triangle count
#useful for optimizing LOD packs or finding bottlenecks
triangle_profiler: False

#editorids of worldspaces for which merged meshes will not be generated
worldspaces_to_skip:
 - "AnvilCastleCourtyardWorld"
 - "AnvilWorld"
 - "BANSkingradOutskirts"
 - "BravilWorld"
 - "BrumaWorld"
 - "CheydinhalWorld"
 - "ChorrolWorld"
 - "E3Kvatch"
 - "ICArboretumDistrict"
 - "ICArenaDistrict"
 - "ICAristocraticDistrict"
 - "ICDiplomaticDistrict"
 - "ICElvenGardensDistrict"
 - "ICImperialPalace"
 - "ICImperialPalaceMQ16"
 - "ICImperialPrisonDistrict"
 - "ICMarketDistrict"
 - "ICTalosPlazaDistrict"
 - "ICTempleDistrict"
 - "ICTempleDistrictMQ16"
 - "ICTheArcaneUniversity"
 - "KvatchEast"
 - "KvatchEntrance"
 - "KvatchPlaza"
 - "LeyawiinWorld"
 - "SEDementiaGarden"
 - "SEManiaGarden"
 - "SENSBliss"
 - "SENSCrucible"
 - "SENSPalace"
 - "SETest"
 - "SETestCylarne"
 - "SETheFringe"
 - "SETestGrant"
 - "SEVitharnWorld"
 - "SkingradWorld"
 - "TestExRuin"
 - "TestFortRuinsExtWarehouse"
 - "TestGragtown"
 - "TestMatt"
 - "TestWorld"
 - "TGTempleOfTheEmperorZero"
 - "ToddTestLand2"
 - "Toddland"

#meshes that are not going to be merged -- lowercase without _far
meshes_to_skip:
 - "oblivion\\environment\\fxoblivionlightbeamlong01.nif"
 - "ICLOD\\ICMarket.nif"
 - "ICLOD\\ICTalosPlaza.nif"
 - "ICLOD\\ICTemple.nif"
 - "ICLOD\\ICElvenGardens.nif"
 - "ICLOD\\ICArena.nif"
 - "ICLOD\\ICGreenEmperorWay.nif"
 - "ICLOD\\ICArboretum.nif"
 - "ICLOD\\ICArcane.nif"
 - "ICLOD\\ICPrison.nif"
 - "ICLOD\\BC_Arboretum.nif"
 - "ICLOD\\BC_Arcane.nif"
 - "ICLOD\\BC_Arcane_Towers.nif"
 - "ICLOD\\BC_Arena.nif"
 - "ICLOD\\BC_Diplomatic.nif"
 - "ICLOD\\BC_ElvenGardens.nif"
 - "ICLOD\\BC_GreenEmperorWay.nif"
 - "ICLOD\\BC_Market.nif"
 - "ICLOD\\BC_Prison.nif"
 - "ICLOD\\BC_Talos_Plaza.nif"
 - "ICLOD\\BC_Temple.nif"
 - "LOD\\AnvilLOD.nif"
 - "LOD\\BC_AnvilLOD.nif"
 - "LOD\\ChorrolLOD.nif"
 - "LOD\\BC_ChorrolLOD.nif"
 - "LOD\\BC_ChorrolCastleLOD.nif"
 - "LOD\\BrumaLOD.nif"
 - "LOD\\BC_BrumaLOD.nif" 
 - "LOD\\BC_BrumaCastleLOD.nif"
 - "LOD\\CheydinhalLOD.nif"
 - "LOD\\BC_CheydinhalLOD.nif"
 - "LOD\\BC_CheydinhalCastleLOD.nif"
 - "LOD\\BravilLOD.nif"
 - "LOD\\BC_BravilLOD.nif"
 - "LOD\\BC_BravilCastleLOD.nif"
 - "LOD\\SkingradLOD.nif"
 - "LOD\\BC_SkingradLOD.nif"
 - "LOD\\BC_SkingradCastleLOD.nif"
 - "LOD\\LeyawiinLOD.nif"
 - "LOD\\BC_LeyawiinLOD.nif"
 - "LOD\\BC_LeyawiinCastleLOD.nif"
 - "LOD\\KvatchLOD.nif"
 
#list of bsas not loaded by esps
#if doesn't exist will be skipped 
hardcoded_bsas:
 - "Oblivion - Meshes.bsa"
 - "Oblivion - Misc.bsa"
 - "Oblivion - Textures - Compressed.bsa"
 - "N - Meshes.bsa"
 - "N - Textures1.bsa"
 - "N - Textures2.bsa"
 - "N - Misc.bsa"
 
#if True only vwd flagged references will be merged
only_vwd_flagged_refs: False
